version: '3'

services:
  flask-app:
    image: your-flask-image
    ports:
      - "6000:5000"
    networks:
      - my_network
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

networks:
  my_network:
    driver: bridge      
