version: '3'

services:
  flask-app:
    image: receipt-processor-challenge:latest
    ports:
      - "6000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - receiptchallenege_network
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - receiptchallenege_network  

networks:
  receiptchallenege_network:
    driver: bridge      
